-- Generated by scripts/gen_rag_views.py from config/catalog/production*.yaml — review before running.
-- Database: Production  (tsql)
-- Run as a DBA. This script only creates a schema, views and a read-only login; it never
-- touches existing objects. See docs/DATA_ACCESS.md section 1 and 6.

USE [Production];
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')
    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');
GO

-- Pre-Production Meeting (PPM) records with the factory, unit, style, file, PO number, order quantity, meeting date, first/last PCD, first/last shipment date, meeting status and cut-approval status.
CREATE OR ALTER VIEW rag.vw_PPMMeeting AS
SELECT
  m.MeetingId,
  CASE m.FactoryID
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE m.FactoryID
  END AS FactoryID,
  m.Unit,
  m.BuyerID,
  m.StyleID,
  m.FileRefID,
  m.ExportPONumber,
  m.OrderQuantity,
  CAST(m.PPMDate AS date)             AS PPMDate,
  m.PPMTime,
  CAST(m.FirstPCD AS date)            AS FirstPCD,
  CAST(m.LastPCD AS date)             AS LastPCD,
  CAST(m.FirstShipmentDate AS date)   AS FirstShipmentDate,
  CAST(m.LastShipmentDate AS date)    AS LastShipmentDate,
  m.Status,
  m.Location,
  m.GPQApprovalStatus,
  m.InitialCutApprovalStatus,
  m.InitialCutApprovalQty,
  m.BulkCutApprovalStatus,
  m.BulkCutApprovalQty,
  m.Season
FROM PPM.PPMMeetings m
GO

-- History of PPM meeting reschedules with old/new dates and remarks.
CREATE OR ALTER VIEW rag.vw_PPMMeetingReschedule AS
SELECT
  r.LogId,
  r.MeetingId,
  CAST(r.OldPPMDate AS date) AS OldPPMDate,
  CAST(r.NewPPMDate AS date) AS NewPPMDate,
  r.OldPPMTime,
  r.NewPPMTime,
  r.OldLocation,
  r.NewLocation,
  CAST(r.OldPCD AS date) AS OldPCD,
  CAST(r.NewPCD AS date) AS NewPCD,
  r.Remarks,
  r.CreatedBy,
  CAST(r.CreatedDate AS date) AS CreatedDate
FROM PPM.PPMMeetingRescheduleLog r
GO

-- Department completion checklist for each PPM meeting.
CREATE OR ALTER VIEW rag.vw_PPMDepartmentChecklist AS
SELECT
  c.ChecklistItemId,
  c.MeetingId,
  c.DepartmentCode,
  c.ChecklistItem,
  c.ItemDescription,
  c.IsRequired,
  c.IsCompleted,
  CAST(c.CompletedDate AS date) AS CompletedDate,
  c.CompletedBy
FROM PPM.DepartmentCompletionChecklist c
GO

-- One dedicated read-only login, SELECT on schema rag only (no dbo, no EXECUTE, no linked servers):
-- CREATE LOGIN rag_reader WITH PASSWORD = '<strong password>';
-- CREATE USER rag_reader FOR LOGIN rag_reader;
-- GRANT SELECT ON SCHEMA::rag TO rag_reader;
