-- Generated by scripts/gen_rag_views.py from config/catalog/production*.yaml — review before running.
-- Database: Production  (tsql)
-- Run as a DBA. This script only creates a schema and views; it never touches existing objects.
-- The login and its permissions are in the DBA request sent with this script. See also
-- docs/DATA_ACCESS.md sections 1 and 6.

-- Row scope: a view with a factory column returns only the rows of the factories named in the
-- session context key 'rag_factories' (comma list, or * for all); with no value it returns nothing.
-- To test as a DBA:
--   EXEC sp_set_session_context @key = N'rag_factories', @value = N'*';
--   SELECT TOP (5) * FROM rag.vw_<name>;
--   EXEC sp_set_session_context @key = N'rag_factories', @value = N'TAL';   -- then only TAL rows

USE [Production];
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')
    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');
GO

-- Pre-Production Meeting (PPM) records with the factory, unit, style, file, PO number, order quantity, meeting date, first/last PCD, first/last shipment date, meeting status and cut-approval status.
CREATE OR ALTER VIEW rag.vw_PPMMeeting AS
SELECT * FROM (
SELECT
  m.MeetingId,
  CASE m.FactoryID
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE m.FactoryID
  END AS FactoryID,
  m.Unit,
  m.BuyerID,
  m.StyleID,
  m.FileRefID,
  m.ExportPONumber,
  m.OrderQuantity,
  CAST(m.PPMDate AS date)             AS PPMDate,
  m.PPMTime,
  CAST(m.FirstPCD AS date)            AS FirstPCD,
  CAST(m.LastPCD AS date)             AS LastPCD,
  CAST(m.FirstShipmentDate AS date)   AS FirstShipmentDate,
  CAST(m.LastShipmentDate AS date)    AS LastShipmentDate,
  m.Status,
  m.Location,
  m.GPQApprovalStatus,
  m.InitialCutApprovalStatus,
  m.InitialCutApprovalQty,
  m.BulkCutApprovalStatus,
  m.BulkCutApprovalQty,
  m.Season
FROM PPM.PPMMeetings m
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[FactoryID] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- History of PPM meeting reschedules with old/new dates and remarks.
CREATE OR ALTER VIEW rag.vw_PPMMeetingReschedule AS
SELECT * FROM (
SELECT
  r.LogId,
  r.MeetingId,
  CAST(r.OldPPMDate AS date) AS OldPPMDate,
  CAST(r.NewPPMDate AS date) AS NewPPMDate,
  r.OldPPMTime,
  r.NewPPMTime,
  r.OldLocation,
  r.NewLocation,
  CAST(r.OldPCD AS date) AS OldPCD,
  CAST(r.NewPCD AS date) AS NewPCD,
  r.Remarks,
  r.CreatedBy,
  CAST(r.CreatedDate AS date) AS CreatedDate,
  CASE m.FactoryID
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE m.FactoryID
  END AS FactoryID
FROM PPM.PPMMeetingRescheduleLog r
LEFT JOIN PPM.PPMMeetings m ON m.MeetingId = r.MeetingId
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[FactoryID] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- Department completion checklist for each PPM meeting.
CREATE OR ALTER VIEW rag.vw_PPMDepartmentChecklist AS
SELECT * FROM (
SELECT
  c.ChecklistItemId,
  c.MeetingId,
  c.DepartmentCode,
  c.ChecklistItem,
  c.ItemDescription,
  c.IsRequired,
  c.IsCompleted,
  CAST(c.CompletedDate AS date) AS CompletedDate,
  c.CompletedBy,
  CASE m.FactoryID
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE m.FactoryID
  END AS FactoryID
FROM PPM.DepartmentCompletionChecklist c
LEFT JOIN PPM.PPMMeetings m ON m.MeetingId = c.MeetingId
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[FactoryID] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

