-- Generated by scripts/gen_rag_views.py from config/catalog/bitopisplint*.yaml — review before running.
-- Database: BitopiSplint  (tsql)
-- Run as a DBA. This script only creates a schema, views and a read-only login; it never
-- touches existing objects. See docs/DATA_ACCESS.md section 1 and 6.

USE [BitopiSplint];
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')
    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');
GO

-- Confirmed export orders with the plan cut date (PCD), ship date, factory, merchandiser, buyer name and current status. Excludes financial values (rate, order value) intentionally.
CREATE OR ALTER VIEW rag.vw_ExportOrder AS
SELECT
  eo.ExportOrderID,
  eo.ExportOrderNo,
  eo.ExportPONo,
  eo.FileRefID,
  fr.FileRefNo,
  buyer.ContactName        AS Buyer,
  eo.BuyerStyleNo,
  sm.StyleName,
  eo.OrderQty,
  eo.UOM,
  CAST(eo.PCD AS date)             AS PCD,
  CAST(eo.PlanCutOffDate AS date)  AS PlanCutOffDate,
  CAST(eo.ShipDate AS date)        AS ShipDate,
  CAST(eo.ExfactoryDate AS date)   AS ExfactoryDate,
  eo.ExportOrderStatus,
  eo.ExportOrderCategory,
  eo.ShipmentStatus,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory,
  fr.Merchandiser,
  fr.Season,
  eo.PCDConfirmation
FROM dbo.ExportOrder eo
LEFT JOIN dbo.FileRef fr        ON fr.FileRefID  = eo.FileRefID
LEFT JOIN dbo.Contact_Master buyer ON buyer.ContactID = fr.Buyer
LEFT JOIN dbo.Style_Master sm   ON sm.StyleId    = eo.StyleID
GO

-- Buyer file references with product category, fabric/trims in-house dates and current status. One file usually spans several export orders.
CREATE OR ALTER VIEW rag.vw_FileRef AS
SELECT
  fr.FileRefID,
  fr.FileRefNo,
  buyer.ContactName        AS Buyer,
  fr.BuyerDepartment,
  fr.ProductCategory,
  CAST(fr.FileRefDate      AS date) AS FileRefDate,
  CAST(fr.LastDeliveryDate AS date) AS LastDeliveryDate,
  fr.OrderQty,
  fr.FileStatus,
  fr.OrderType,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory,
  fr.Merchandiser,
  sm.StyleName,
  fr.Season,
  CAST(fr.FabricFirstInhanseDate  AS date) AS FabricFirstInhanseDate,
  CAST(fr.FabricSecondInhanseDate AS date) AS FabricSecondInhanseDate,
  CAST(fr.TrimsFirstInhanseDate   AS date) AS TrimsFirstInhanseDate,
  CAST(fr.TrimsSecondInhanseDate  AS date) AS TrimsSecondInhanseDate
FROM dbo.FileRef fr
LEFT JOIN dbo.Contact_Master buyer ON buyer.ContactID = fr.Buyer
LEFT JOIN dbo.Style_Master sm      ON sm.StyleId      = fr.StyleID
GO

-- Breakdown of an export order into colours and sizes with quantities.
CREATE OR ALTER VIEW rag.vw_ExportOrderColorSize AS
SELECT
  eo.ExportOrderID,
  eo.ExportPONo,
  ec.ColorName,
  ec.Shade,
  ecs.SizeCode,
  ecs.SizeQty,
  ec.ColorQty
FROM dbo.ExportOrder eo
INNER JOIN dbo.ExportColor ec      ON ec.ExportOrderID = eo.ExportOrderID
INNER JOIN dbo.ExportColorSize ecs ON ecs.ExportColorID = ec.ExportColorID AND ecs.ExportOrderID = eo.ExportOrderID
GO

-- History of PCD and ship-date changes from the ExportOrderBack audit table (4M+ rows). KNOWN LIMITATION: ExportOrderBack has no index on ExportOrderID (only on Serial), so a WHERE ExportOrderID = @eo filter is a full table scan and can exceed the 10s guard timeout. A DBA should add CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack(ExportOrderID) when materialising the real rag.* views (docs/DATA_ACCESS.md §6); until then this view may time out on some orders.
CREATE OR ALTER VIEW rag.vw_PCDChangeHistory AS
SELECT
  eob.ExportOrderID,
  eob.VersionNo,
  CAST(eob.PCD      AS date) AS PCD,
  CAST(eob.ShipDate AS date) AS ShipDate,
  eob.UpdatedBy,
  CAST(eob.DateUpdated AS date) AS DateUpdated
FROM dbo.ExportOrderBack eob
GO

-- Register of cancelled export orders with cancellation date and reason (remarks).
CREATE OR ALTER VIEW rag.vw_CancelledExportOrder AS
SELECT
  cel.ExportOrderID,
  cel.FileRefNo,
  cel.CompanyName,
  cel.UnitName,
  cel.PCD,
  cel.ShipDate,
  cel.OrderQty,
  cel.ExportOrderStatus,
  cel.CancelledBy,
  cel.CancelledDate,
  cel.Remarks
FROM dbo.CancellExportOrderList cel
GO

-- One dedicated read-only login, SELECT on schema rag only (no dbo, no EXECUTE, no linked servers):
-- CREATE LOGIN rag_reader WITH PASSWORD = '<strong password>';
-- CREATE USER rag_reader FOR LOGIN rag_reader;
-- GRANT SELECT ON SCHEMA::rag TO rag_reader;

-- Recommended: ExportOrderBack (4M+ rows) has no index on ExportOrderID, only on Serial,
-- so rag.vw_PCDChangeHistory does a full scan per lookup and can exceed a 10s query timeout:
-- CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack(ExportOrderID);
