-- Generated by scripts/gen_rag_views.py from config/catalog/bitopisplint*.yaml — review before running.
-- Database: BitopiSplint  (tsql)
-- Run as a DBA. This script only creates a schema and views; it never touches existing objects.
-- The login and its permissions are in the DBA request sent with this script. See also
-- docs/DATA_ACCESS.md sections 1 and 6.

-- Row scope: a view with a factory column returns only the rows of the factories named in the
-- session context key 'rag_factories' (comma list, or * for all); with no value it returns nothing.
-- To test as a DBA:
--   EXEC sp_set_session_context @key = N'rag_factories', @value = N'*';
--   SELECT TOP (5) * FROM rag.vw_<name>;
--   EXEC sp_set_session_context @key = N'rag_factories', @value = N'TAL';   -- then only TAL rows

USE [BitopiSplint];
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')
    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');
GO

-- Confirmed export orders with the plan cut date (PCD), ship date, factory, merchandiser, buyer name and current status. Excludes financial values (rate, order value) intentionally.
CREATE OR ALTER VIEW rag.vw_ExportOrder AS
SELECT * FROM (
SELECT
  eo.ExportOrderID,
  eo.ExportOrderNo,
  eo.ExportPONo,
  eo.FileRefID,
  fr.FileRefNo,
  buyer.ContactName        AS Buyer,
  eo.BuyerStyleNo,
  sm.StyleName,
  eo.OrderQty,
  eo.UOM,
  CAST(eo.PCD AS date)             AS PCD,
  CAST(eo.PlanCutOffDate AS date)  AS PlanCutOffDate,
  CAST(eo.ShipDate AS date)        AS ShipDate,
  CAST(eo.ExfactoryDate AS date)   AS ExfactoryDate,
  eo.ExportOrderStatus,
  eo.ExportOrderCategory,
  eo.ShipmentStatus,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory,
  fr.Merchandiser,
  fr.Season,
  eo.PCDConfirmation
FROM dbo.ExportOrder eo
LEFT JOIN dbo.FileRef fr        ON fr.FileRefID  = eo.FileRefID
LEFT JOIN dbo.Contact_Master buyer ON buyer.ContactID = fr.Buyer
LEFT JOIN dbo.Style_Master sm   ON sm.StyleId    = eo.StyleID
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[Factory] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- Buyer file references with product category, fabric/trims in-house dates and current status. One file usually spans several export orders.
CREATE OR ALTER VIEW rag.vw_FileRef AS
SELECT * FROM (
SELECT
  fr.FileRefID,
  fr.FileRefNo,
  buyer.ContactName        AS Buyer,
  fr.BuyerDepartment,
  fr.ProductCategory,
  CAST(fr.FileRefDate      AS date) AS FileRefDate,
  CAST(fr.LastDeliveryDate AS date) AS LastDeliveryDate,
  fr.OrderQty,
  fr.FileStatus,
  fr.OrderType,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory,
  fr.Merchandiser,
  sm.StyleName,
  fr.Season,
  CAST(fr.FabricFirstInhanseDate  AS date) AS FabricFirstInhanseDate,
  CAST(fr.FabricSecondInhanseDate AS date) AS FabricSecondInhanseDate,
  CAST(fr.TrimsFirstInhanseDate   AS date) AS TrimsFirstInhanseDate,
  CAST(fr.TrimsSecondInhanseDate  AS date) AS TrimsSecondInhanseDate
FROM dbo.FileRef fr
LEFT JOIN dbo.Contact_Master buyer ON buyer.ContactID = fr.Buyer
LEFT JOIN dbo.Style_Master sm      ON sm.StyleId      = fr.StyleID
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[Factory] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- Breakdown of an export order into colours and sizes with quantities.
CREATE OR ALTER VIEW rag.vw_ExportOrderColorSize AS
SELECT * FROM (
SELECT
  eo.ExportOrderID,
  eo.ExportPONo,
  ec.ColorName,
  ec.Shade,
  ecs.SizeCode,
  ecs.SizeQty,
  ec.ColorQty,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory
FROM dbo.ExportOrder eo
INNER JOIN dbo.ExportColor ec      ON ec.ExportOrderID = eo.ExportOrderID
INNER JOIN dbo.ExportColorSize ecs ON ecs.ExportColorID = ec.ExportColorID AND ecs.ExportOrderID = eo.ExportOrderID
LEFT JOIN dbo.FileRef fr           ON fr.FileRefID = eo.FileRefID
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[Factory] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- History of PCD and ship-date changes from the ExportOrderBack audit table (4M+ rows). KNOWN LIMITATION: ExportOrderBack has no index on ExportOrderID (only on Serial), so a WHERE ExportOrderID = @eo filter is a full table scan and can exceed the 10s guard timeout. A DBA should add CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack(ExportOrderID) when materialising the real rag.* views (docs/DATA_ACCESS.md §6); until then this view may time out on some orders.
CREATE OR ALTER VIEW rag.vw_PCDChangeHistory AS
SELECT * FROM (
SELECT
  eob.ExportOrderID,
  eob.VersionNo,
  CAST(eob.PCD      AS date) AS PCD,
  CAST(eob.ShipDate AS date) AS ShipDate,
  eob.UpdatedBy,
  CAST(eob.DateUpdated AS date) AS DateUpdated,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory
FROM dbo.ExportOrderBack eob
LEFT JOIN dbo.ExportOrder eo ON eo.ExportOrderID = eob.ExportOrderID
LEFT JOIN dbo.FileRef fr     ON fr.FileRefID = eo.FileRefID
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[Factory] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- Register of cancelled export orders with cancellation date and reason (remarks).
CREATE OR ALTER VIEW rag.vw_CancelledExportOrder AS
SELECT * FROM (
SELECT
  cel.ExportOrderID,
  cel.FileRefNo,
  cel.CompanyName,
  cel.UnitName,
  cel.PCD,
  cel.ShipDate,
  cel.OrderQty,
  cel.ExportOrderStatus,
  cel.CancelledBy,
  cel.CancelledDate,
  cel.Remarks,
  CASE fr.Factory
    WHEN '06' THEN 'TAL' WHEN '04' THEN 'BGL' WHEN '09' THEN 'RHL'
    WHEN '08' THEN 'KTL' WHEN '11' THEN 'CKDL' ELSE fr.Factory
  END AS Factory
FROM dbo.CancellExportOrderList cel
LEFT JOIN dbo.ExportOrder eo ON eo.ExportOrderID = cel.ExportOrderID
LEFT JOIN dbo.FileRef fr     ON fr.FileRefID = eo.FileRefID
) AS v
WHERE CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) = N'*'
   OR CHARINDEX(N',' + v.[Factory] + N',', N',' + CAST(SESSION_CONTEXT(N'rag_factories') AS nvarchar(4000)) + N',') > 0
GO

-- Recommended: ExportOrderBack (4M+ rows) has no index on ExportOrderID, only on Serial,
-- so rag.vw_PCDChangeHistory scans the whole table per lookup (10-22 s cold, measured):
-- CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack (ExportOrderID)
--     INCLUDE (VersionNo, PCD, ShipDate, UpdatedBy, DateUpdated);
