"""Render the CREATE SCHEMA / CREATE VIEW script a DBA would run to materialise the `rag.*` views for
real, from the same `definition:` fields the app uses as virtual views today.

Views with a `scope_column:` are generated with the per-user row filter (PRD FR-4.4, data/scope_sql.py):
they return only the rows of the factories the connection's session context names, and nothing when it
names none.

This script only WRITES a .sql file to disk — it never connects to a database or executes anything.
Usage: python scripts/gen_rag_views.py [--out docs/schema]
"""
import argparse, _path  # noqa: F401
from pathlib import Path

from ragbot.data.catalog import load_catalogs
from ragbot.data.scope_sql import SESSION_KEY, session_filtered

ROOT = Path(__file__).resolve().parents[1]


def render(name: str, cat) -> str:
    lines = [
        f"-- Generated by scripts/gen_rag_views.py from config/catalog/{name.lower()}*.yaml — review before running.",
        f"-- Database: {name}  ({cat.dialect})",
        "-- Run as a DBA. This script only creates a schema and views; it never touches existing objects.",
        "-- The login and its permissions are in the DBA request sent with this script. See also",
        "-- docs/DATA_ACCESS.md sections 1 and 6.",
        "",
    ]
    if cat.dialect == "tsql":
        lines += [
            "-- Row scope: a view with a factory column returns only the rows of the factories named in the",
            f"-- session context key '{SESSION_KEY}' (comma list, or * for all); with no value it returns nothing.",
            "-- To test as a DBA:",
            f"--   EXEC sp_set_session_context @key = N'{SESSION_KEY}', @value = N'*';",
            "--   SELECT TOP (5) * FROM rag.vw_<name>;",
            f"--   EXEC sp_set_session_context @key = N'{SESSION_KEY}', @value = N'TAL';   -- then only TAL rows",
            "",
            f"USE [{name}];",
            "GO",
            "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')",
            "    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');",
            "GO",
            "",
        ]
        for v in cat.views:
            if not v.definition:
                continue
            bare = v.name.split(".")[-1]
            body = session_filtered(v.definition, v.scope_column) if v.scope_column else v.definition.strip()
            lines += [f"-- {v.description.strip()}" if v.description else "",
                      f"CREATE OR ALTER VIEW rag.{bare} AS", body, "GO", ""]
        if name == "BitopiSplint":
            lines += [
                "-- Recommended: ExportOrderBack (4M+ rows) has no index on ExportOrderID, only on Serial,",
                "-- so rag.vw_PCDChangeHistory scans the whole table per lookup (10-22 s cold, measured):",
                "-- CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack (ExportOrderID)",
                "--     INCLUDE (VersionNo, PCD, ShipDate, UpdatedBy, DateUpdated);",
            ]
    else:
        lines += ["-- CREATE DATABASE rag;", ""]
        for v in cat.views:
            if not v.definition:
                continue
            bare = v.name.split(".")[-1]
            lines += [f"-- {v.description.strip()}" if v.description else "",
                      f"CREATE OR REPLACE VIEW rag.{bare} AS", v.definition.strip() + ";", ""]
        lines += [
            "-- CREATE USER 'rag_reader'@'%' IDENTIFIED BY '<strong password>';",
            "-- GRANT SELECT ON rag.* TO 'rag_reader'@'%';",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/schema")
    a = ap.parse_args()
    cats = load_catalogs()
    if not cats:
        print("no catalogs loaded under config/catalog/*.yaml"); raise SystemExit(1)
    out_dir = ROOT / a.out
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, cat in cats.items():
        path = out_dir / f"rag_views_{name.lower()}.sql"
        path.write_text(render(name, cat), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
