"""Render the CREATE SCHEMA / CREATE VIEW / CREATE LOGIN script a DBA would run to materialise the
`rag.*` views for real, from the same `definition:` fields the app uses as virtual views today.

This script only WRITES a .sql file to disk — it never connects to a database or executes anything.
Usage: python scripts/gen_rag_views.py [--out docs/schema]
"""
import argparse, _path  # noqa: F401
from pathlib import Path

from ragbot.data.catalog import load_catalogs

ROOT = Path(__file__).resolve().parents[1]


def render(name: str, cat) -> str:
    lines = [
        f"-- Generated by scripts/gen_rag_views.py from config/catalog/{name.lower()}*.yaml — review before running.",
        f"-- Database: {name}  ({cat.dialect})",
        "-- Run as a DBA. This script only creates a schema, views and a read-only login; it never",
        "-- touches existing objects. See docs/DATA_ACCESS.md section 1 and 6.",
        "",
    ]
    if cat.dialect == "tsql":
        lines += [
            f"USE [{name}];",
            "GO",
            "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'rag')",
            "    EXEC('CREATE SCHEMA rag AUTHORIZATION dbo');",
            "GO",
            "",
        ]
        for v in cat.views:
            if not v.definition:
                continue
            bare = v.name.split(".")[-1]
            lines += [f"-- {v.description.strip()}" if v.description else "",
                     f"CREATE OR ALTER VIEW rag.{bare} AS", v.definition.strip(), "GO", ""]
        lines += [
            "-- One dedicated read-only login, SELECT on schema rag only (no dbo, no EXECUTE, no linked servers):",
            "-- CREATE LOGIN rag_reader WITH PASSWORD = '<strong password>';",
            f"-- CREATE USER rag_reader FOR LOGIN rag_reader;",
            "-- GRANT SELECT ON SCHEMA::rag TO rag_reader;",
        ]
        if name == "BitopiSplint":
            lines += [
                "",
                "-- Recommended: ExportOrderBack (4M+ rows) has no index on ExportOrderID, only on Serial,",
                "-- so rag.vw_PCDChangeHistory does a full scan per lookup and can exceed a 10s query timeout:",
                "-- CREATE INDEX IX_ExportOrderBack_ExportOrderID ON dbo.ExportOrderBack(ExportOrderID);",
            ]
    else:
        lines += ["-- CREATE DATABASE rag;", ""]
        for v in cat.views:
            if not v.definition:
                continue
            bare = v.name.split(".")[-1]
            lines += [f"-- {v.description.strip()}" if v.description else "",
                     f"CREATE OR REPLACE VIEW rag.{bare} AS", v.definition.strip() + ";", ""]
        lines += [
            "-- CREATE USER 'rag_reader'@'%' IDENTIFIED BY '<strong password>';",
            "-- GRANT SELECT ON rag.* TO 'rag_reader'@'%';",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/schema")
    a = ap.parse_args()
    cats = load_catalogs()
    if not cats:
        print("no catalogs loaded under config/catalog/*.yaml"); raise SystemExit(1)
    out_dir = ROOT / a.out
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, cat in cats.items():
        path = out_dir / f"rag_views_{name.lower()}.sql"
        path.write_text(render(name, cat), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
